name: icecap
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs=23.1.0
  - aws-c-auth=0.7.8
  - aws-c-cal=0.6.9
  - aws-c-common=0.9.10
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.2
  - aws-c-http=0.7.14
  - aws-c-io=0.13.36
  - aws-c-mqtt=0.9.10
  - aws-c-s3=0.4.4
  - aws-c-sdkutils=0.1.13
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.24.11
  - aws-sdk-cpp=1.11.210
  - blosc=1.21.5
  - bokeh=3.3.2
  - bottleneck=1.3.7
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.23.0
  - ca-certificates=2024.3.11
  - cartopy=0.22.0
  - cdsapi=0.6.1
  - certifi=2024.2.2
  - cf_xarray=0.8.6
  - cffi=1.16.0
  - cfgrib=0.9.10.4
  - cftime=1.6.3
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - cmocean=3.0.3
  - colorama=0.4.6
  - colorspacious=1.1.2
  - contourpy=1.2.0
  - cycler=0.12.1
  - cytoolz=0.12.2
  - dask=2023.12.0
  - dask-core=2023.12.0
  - distributed=2023.12.0
  - eccodes=2.32.1
  - ecflow=5.11.4
  - esmf=8.4.2
  - esmpy=8.4.2
  - findlibs=0.0.5
  - fonttools=4.46.0
  - freetype=2.12.1
  - fsspec=2023.12.2
  - geos=3.12.1
  - gettext=0.21.1
  - gflags=2.2.2
  - glib=2.78.3
  - glib-tools=2.78.3
  - glog=0.6.0
  - gst-plugins-base=1.22.7
  - gstreamer=1.22.7
  - hdf4=4.2.15
  - hdf5=1.14.3
  - icu=73.2
  - idna=3.6
  - importlib-metadata=7.0.0
  - importlib_metadata=7.0.0
  - jasper=4.1.0
  - jinja2=3.1.2
  - joblib=1.4.0
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.1.2
  - libarrow=14.0.1
  - libarrow-acero=14.0.1
  - libarrow-dataset=14.0.1
  - libarrow-flight=14.0.1
  - libarrow-flight-sql=14.0.1
  - libarrow-gandiva=14.0.1
  - libarrow-substrait=14.0.1
  - libblas=3.9.0
  - libboost=1.82.0
  - libboost-devel=1.82.0
  - libboost-headers=1.82.0
  - libboost-python=1.82.0
  - libboost-python-devel=1.82.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcrc32c=1.1.2
  - libcurl=8.5.0
  - libcxx=16.0.6
  - libdeflate=1.19
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.78.3
  - libgoogle-cloud=2.12.0
  - libgrpc=1.59.3
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libogg=1.3.4
  - libopenblas=0.3.25
  - libopus=1.3.1
  - libparquet=14.0.1
  - libpnetcdf=1.12.3
  - libpng=1.6.39
  - libpq=16.1
  - libprotobuf=4.24.4
  - libre2-11=2023.06.02
  - libsqlite=3.44.2
  - libssh2=1.11.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libvorbis=1.3.7
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.12.3
  - libzip=1.10.1
  - libzlib=1.2.13
  - llvm-openmp=17.0.6
  - llvmlite=0.41.1
  - locket=1.0.0
  - lz4=4.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.8.2
  - matplotlib-base=3.8.2
  - mpi=1.0
  - mpich=4.1.2
  - msgpack-python=1.0.7
  - munkres=1.1.4
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - ncurses=6.4.20240210
  - netcdf-fortran=4.6.1
  - netcdf4=1.6.5
  - nspr=4.35
  - nss=3.95
  - numba=0.58.1
  - numpy=1.26.2
  - openjpeg=2.5.0
  - openssl=3.2.0
  - orc=1.9.2
  - packaging=23.2
  - pandas=1.5.3
  - parallelio=2.6.2
  - partd=1.4.1
  - patsy=0.5.3
  - pcre2=10.42
  - pillow=10.1.0
  - pip=23.3.1
  - proj=9.3.1
  - properscoring=0.1
  - psutil=5.9.5
  - pthread-stubs=0.4
  - pyarrow=14.0.1
  - pyarrow-hotfix=0.6
  - pycparser=2.21
  - pyparsing=3.1.1
  - pyproj=3.6.1
  - pyshp=2.3.1
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.8.2
  - python-eccodes=1.6.1
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - qt-main=5.15.8
  - re2=2023.06.02
  - readline=8.2
  - requests=2.31.0
  - scikit-learn=1.4.2
  - scipy=1.11.4
  - setuptools=68.2.2
  - shapely=2.0.2
  - six=1.16.0
  - snappy=1.1.10
  - sortedcontainers=2.4.0
  - sparse=0.14.0
  - sqlite=3.41.2
  - statsmodels=0.14.0
  - tblib=3.0.0
  - threadpoolctl=2.2.0
  - tk=8.6.13
  - toolz=0.12.0
  - tornado=6.3.3
  - tqdm=4.66.1
  - tzdata=2023c
  - unicodedata2=15.1.0
  - urllib3=2.1.0
  - wheel=0.41.2
  - xarray=2023.12.0
  - xesmf=0.8.2
  - xhistogram=0.3.2
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xskillscore=0.0.26
  - xyzservices=2023.10.1
  - xz=5.4.5
  - yaml=0.2.5
  - zict=3.0.0
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
